# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDFHmyiqfhcu_GubYbVohfHRrX1URT45
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0.0001,20,0.0001)

def logexp(x):
  return np.log(x)

def tangent_line(f,x_0,x_start,x_end,linestyle):
  epsilon = 0.0000001
  deriv = ((f(x_0+epsilon) - f(x_0)) / epsilon)
  x = np.linspace(x_start,x_end,200)
  y = f(x) 
  y_0 = f(x_0)
  y_tan = deriv * (x - x_0) + y_0 
  plt.plot(x,y_tan,linestyle, label='Tangent line on X=%i'%x_0)

plt.figure(figsize=(12,8))
plt.plot(x,logexp(x),label='tan')
tangent_line(logexp,1,0,3,'r--')
tangent_line(logexp,2,0.8,4,'k--')
tangent_line(logexp,3,1.8,5,'y--')
plt.legend()
plt.ylim(-5,2.5)
plt.xlim(0,15)
plt.xticks(np.arange(0,15,1))
plt.yticks(np.arange(-5,2.5,0.5))
plt.gca().set_aspect('equal', adjustable='box')
plt.grid()